__title__ = "spacy_yake"
__version__ = "0.1.0"
__summary__ = "spaCy pipeline component for Yake! - Keyword extraction"
__author__ = "Tal Almagor"
__email__ = "almagoric@gmail.com"
__license__ = "GPL"
__url__ = "https://github.com/talmago/spacy_yake"
